<?php
//echo "El boton rojo";

function ww_botonRojo_node_view($node, $view_mode) {
if ($node->type == 'article') {
  $link_text = t('Eliminar este nodo');
  $link_options = array(
  'attributes' => array('style' => 'color:#ff0000'),
  );
  $link_markup = l($link_text, "node/$node->nid/delete",
  $link_options);
  $node->content['ww_botonRojo'] = array();
  $node->content['ww_botonRojo']['#markup'] = $link_markup;
  }
}
?>